<a href="https://colab.research.google.com/github/Chidiebere-Ogbuchi/Basic-Python-with-ML1_Hamoye/blob/main/Introduction_to_Python_for_Machine_Learning_Quiz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd

# Specify the URL of the CSV file and the encoding ('ISO-8859-1' or 'latin1')
url = "https://github.com/HamoyeHQ/HDSC-Introduction-to-Python-for-machine-learning/files/7768140/FoodBalanceSheets_E_Africa_NOFLAG.csv"
encoding = "ISO-8859-1"  # or 'latin1'

# Read the CSV file with the specified encoding
FAO = pd.read_csv(url, error_bad_lines=False, encoding=encoding)

# Now, 'FAO' should contain the data from the CSV file without decoding errors

### Data Wrangling

In [3]:
FAO.head(5)

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [4]:
FAO.dtypes

Area Code         int64
Area             object
Item Code         int64
Item             object
Element Code      int64
Element          object
Unit             object
Y2014           float64
Y2015           float64
Y2016           float64
Y2017           float64
Y2018           float64
dtype: object

In [5]:
FAO.describe(include = "all")

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943,60943.000000,60943,60943.000000,60943,60943,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
unique,NaN,49,NaN,119,NaN,18,5,NaN,NaN,NaN,NaN,NaN
top,NaN,Kenya,NaN,Milk - Excluding Butter,NaN,Domestic supply quantity,1000 tonnes,NaN,NaN,NaN,NaN,NaN
freq,NaN,1560,NaN,1262,NaN,5295,40933,NaN,NaN,NaN,NaN,NaN
mean,134.265576,NaN,2687.176706,NaN,3814.856456,NaN,NaN,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,NaN,146.055739,NaN,2212.007033,NaN,NaN,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,NaN,2501.000000,NaN,511.000000,NaN,NaN,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,NaN,2562.000000,NaN,684.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,NaN,2630.000000,NaN,5142.000000,NaN,NaN,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,NaN,2775.000000,NaN,5511.000000,NaN,NaN,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,NaN,2961.000000,NaN,5911.000000,NaN,NaN,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [6]:
#check for missing values
FAO.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

### QUIZ QUESTIONS

In [7]:
#QUESTION 1

# Consider the following list of tuples:

y = [(2, 4), (7, 8), (1, 5, 9)]

# How would you assign element 8 from the list to a variable x?

x = y[1][1]
print(x)

8

In [8]:
##QUESTION 2

# What is the total Protein supply quantity in Madagascar in 2015?

# Filter the data for Madagascar and Protein supply quantity in 2015
madagascar_data = FAO[(FAO['Area'] == 'Madagascar') & (FAO['Element'] == 'Protein supply quantity (g/capita/day)')]

# Get the total protein supply quantity for Madagascar in 2015 ('Y2015' column)
protein_supply_2015 = madagascar_data['Y2015'].sum()

# Now, 'protein_supply_2015' contains the total protein supply quantity in Madagascar in 2015
print("Total Protein Supply Quantity in Madagascar in 2015:", round(protein_supply_2015, 3))

Total Protein Supply Quantity in Madagascar in 2015: 173.05

In [9]:
##QUESTION 3
# How would you check for the number of rows and columns in a pandas DataFrame named df?

FAO.shape

(60943, 12)

In [10]:
# QUESTION 4

# Select columns ‘Y2017’ and ‘Area’, Perform a groupby operation on ‘Area’.  Which of these Areas had the 7th lowest sum in 2017?

sel_area_Y2017 = FAO.groupby('Area')['Y2017'].sum()

sel_area_Y2017.sort_values(ascending=True).iloc[6:7]

Area
Guinea-Bissau    19102.77
Name: Y2017, dtype: float64

In [11]:
# QUESTION 5

# What is the total number of unique countries in the dataset?

# # Calculate the total number of unique countries in the 'Area' column
total_unique_countries = FAO['Area'].nunique()

# Print the result
print("Total number of unique countries in the dataset:", total_unique_countries)

Total number of unique countries in the dataset: 49

In [12]:
# QUESTION 6
# If you have the following list

lst = [[35, 'Portugal', 94], [33, 'Argentina', 93], [30 , 'Brazil', 92]]

col = ['Age','Nationality','Overall']

# How do you create a pandas DataFrame using this list, to look like the table below?

df2 = pd.DataFrame(lst, columns = col, index = [i for i in range(1,4)])
df2

   Age Nationality  Overall
1   35    Portugal       94
2   33   Argentina       93
3   30      Brazil       92

In [13]:
# QUESTION 7
# Select columns ‘Y2017’ and ‘Area’, Perform a groupby operation on ‘Area’.  Which of these Areas had the highest sum in 2017??

sel_area_Y2017.sort_values(ascending=False).iloc[0:1]

Area
Nigeria    1483268.23
Name: Y2017, dtype: float64

In [14]:
# QUESTION 9

# Which year had the least correlation with ‘Element Code’?

# Select the columns of interest, including 'Element Code' and year columns
selected_columns = ['Element Code', 'Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018']
selected_data = FAO[selected_columns]

# Calculate the correlation between 'Element Code' and each year column
correlations = selected_data.corr().abs()

# # Exclude 'Element Code' from the correlation matrix
correlations = correlations.drop(['Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018'], axis=1)

correlations.sort_values(ascending=True, by='Element Code').iloc[0:1]

       Element Code
Y2016      0.023444

In [15]:
# QUESTION 10
# Given the following numpy array

array  = ([[94, 89, 63],

             [93, 92, 48],

             [92, 94, 56]])

# How would you select  the elements in bold and italics from the array?

arr = np.array(array)
arr[:2,1:]

array([[89, 63],
       [92, 48]])

In [16]:
# QUESTION 12

# What would be the output for?

S = [['him', 'sell'], [90, 28, 43]]

S[0][1][1]

'e'

In [17]:
# QUESTION 13
# What is the total number and percentage of missing data in 2014 to 3 decimal places?

# number of missing values in 'Y2014'
missing_values_2014 = FAO['Y2014'].isna().sum()

# total number of rows in the DataFrame
total_rows = len(FAO)

# percentage of missing data in 2014
percentage_missing_2014 = (missing_values_2014 / total_rows) * 100

# Print the total number and percentage of missing data in 2014 (rounded to 3 decimal places)
print("Total Missing Data in 2014:", missing_values_2014)
print("Percentage of Missing Data in 2014:", round(percentage_missing_2014, 3), "%")

Total Missing Data in 2014: 1589
Percentage of Missing Data in 2014: 2.607 %

In [18]:
# QUESTION 14
# Perform a groupby operation on ‘Element’.  What is the total number of the sum of Processing in 2017?

sel_element_is_processing = FAO[FAO['Element']=='Processing']

sel_element_is_processing.groupby('Element')['Y2017'].sum()

Element
Processing    292836.0
Name: Y2017, dtype: float64

In [19]:
# QUESTION 15
# What is the mean and standard deviation across the whole dataset for the year 2017 to 2 decimal places?

Y2017_data = FAO['Y2017']
Y2017_mean = round(Y2017_data.mean(), 2)

Y2017_std = round(Y2017_data.std(), 2)

print(f"for Y2017 the mean is {Y2017_mean} and the standard deviation is {Y2017_std} to 2 dps")

for Y2017 the mean is 140.92 and the standard deviation is 1671.86 to 2 dps

In [20]:
#QUESTION 18
# Given the following python code, what would the output of the code give?

my_tuppy = (1,2,5,8)

my_tuppy[2] = 6

TypeError: ignored

In [21]:
# QUESTION 19
# Perform a groupby operation on ‘Element’.  What year has the highest sum of Stock Variation?

selected_columns = ['Element', 'Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018']
selected_element_data = FAO[selected_columns]
stock_variation_element = selected_element_data[selected_element_data['Element'] == 'Stock Variation']
sve_grouby = stock_variation_element.groupby('Element').sum().T
sve_grouby.sort_values(by = 'Stock Variation', ascending=False).iloc[0:1]

Element  Stock Variation
Y2014           58749.83

In [22]:
#QUESTION 20
# Answer the following questions based on the African food production dataset provided by the FAO website already provided

# What is the total sum of Wine produced in 2015 and 2018 respectively?

# Hint:

# Perform a groupby sum aggregation on ‘Item’

wine_data = FAO[(FAO['Item']=='Wine')]
wine_data_Y2015_2018 = wine_data[['Item','Y2015','Y2018']]

wine_data_Y2015_2018.groupby('Item').sum()

        Y2015    Y2018
Item
Wine  4251.81  4039.32